#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "WPILib.h"
#include "AHRS.h"

class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<CANTalon> drivetrainRightFront;
	static std::shared_ptr<CANTalon> drivetrainRightMiddle;
	static std::shared_ptr<CANTalon> drivetrainRightBack;
	static std::shared_ptr<CANTalon> drivetrainLeftFront;
	static std::shared_ptr<CANTalon> drivetrainLeftMiddle;
	static std::shared_ptr<CANTalon> drivetrainLeftBack;
	static std::shared_ptr<DoubleSolenoid> catapultCatapultSolenoid1;
	static std::shared_ptr<DoubleSolenoid> catapultCatapultSolenoid2;
	static std::shared_ptr<AnalogInput> catapultCatapultBallDetector;
	static std::shared_ptr<CANTalon> pickupArmRetractorMotor1;
	static std::shared_ptr<CANTalon> pickupArmRetractorMotor2;
	static std::shared_ptr<CANTalon> pickupArmPickupMotor;
	static std::shared_ptr<AnalogInput> pickupArmPickupArmBallDetector;
	static std::shared_ptr<Ultrasonic> rangeFinderRangeFinderUltrasonic;
	static std::shared_ptr<DoubleSolenoid> pickupArmFlipperSolenoid;
	static std::shared_ptr<Timer> globalTimer;
	static std::shared_ptr<AHRS> navXNavXMXP;
	static std::shared_ptr<NetworkTable> visonProcessingCameraData;
	static void init();
};
#endif
