#ifndef ROBOTMAP_H
#define ROBOTMAP_H
#include "AHRS.h"
#include "WPILib.h"

class RobotMap {
public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	static std::shared_ptr<DoubleSolenoid> catapultCatapultSolenoid;
	static std::shared_ptr<CANTalon> drivetrainRightMotor1;
	static std::shared_ptr<CANTalon> drivetrainRightMotor2;
	static std::shared_ptr<CANTalon> drivetrainRightMotor3;
	static std::shared_ptr<CANTalon> drivetrainLeftMotor1;
	static std::shared_ptr<CANTalon> drivetrainLeftMotor2;
	static std::shared_ptr<CANTalon> drivetrainLeftMotor3;
	static std::shared_ptr<AnalogInput> rangeFinderSharpSensor1;
	static std::shared_ptr<AnalogInput> rangeFinderSharpSensor2;
	static std::shared_ptr<AnalogInput> rangeFinderSharpSensor3;
	static std::shared_ptr<CANTalon> ballPickupRetractorMotor;
	static std::shared_ptr<CANTalon> ballPickupPickupMotor;
	static void init();
};
#endif
